DROP TABLE IF EXISTS verses;
CREATE TABLE verses(
id INTEGER PRIMARY KEY AUTOINCREMENT,
title TEXT NOT NULL,
content TEXT NOT NULL
);

DROP TABLE IF EXISTS guests;
CREATE TABLE guests(
id INTEGER PRIMARY KEY AUTOINCREMENT,
created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
guestname TEXT NOT NULL,
messagecontent TEXT NOT NULL
);
